//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Movies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movies()
        {
            this.Sessions = new HashSet<Sessions>();
            this.Tickets = new HashSet<Tickets>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public int YearOfIssue { get; set; }
        public int CountryID { get; set; }
        public int GenreID { get; set; }
        public string GenreName
        {
            get
            {
                var genreName = CinemaEntities.GetContext().Genres.FirstOrDefault(x => x.ID == GenreID);
                return genreName.Genre;
            }
        }
        public string Duration { get; set; }
        public string AgeRating { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sessions> Sessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
