//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using CinemaApp.Classes;
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Net.Sockets;
    using System.Windows;

    public partial class RowsAndSeats
    {
        public int ID { get; set; }
        public int HallID { get; set; }
        public string HallName
        {
            get
            {
                var hallName = CinemaEntities.GetContext().Halls.FirstOrDefault(x => x.ID == HallID);
                return hallName.Title;
            }
        }
        public int Row { get; set; }
        public int Seat { get; set; }
        public int HallTypeID { get; set; }
        public bool Status { get; set; }

        public virtual Halls Halls { get; set; }
        public virtual HallTypes HallTypes { get; set; }
    }
}
