//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Sessions
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int HallID { get; set; }
        public string HallName
        {
            get
            {
                var hallName = CinemaEntities.GetContext().Halls.FirstOrDefault(x => x.ID == HallID);
                return hallName.Title;
            }
        }
        public int MovieID { get; set; }
        public string MovieName
        {
            get
            {
                var movieName = CinemaEntities.GetContext().Movies.FirstOrDefault(x => x.ID == MovieID);
                return movieName.Title;
            }
        }
        public double Price { get; set; }
    
        public virtual Halls Halls { get; set; }
        public virtual Movies Movies { get; set; }
    }
}
